AWSTemplateFormatVersion: '2010-09-09'
Description: 'WGA - Main CloudFormation Template'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment

  DeveloperMode:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable developer mode (disables zero trust evaluation)
    
  # 새로 추가할 파라미터들
  UserPoolId:
    Type: String
    Description: ID of the Cognito User Pool
    
  UserPoolClientId:
    Type: String
    Description: ID of the Cognito User Pool Client
    
  UserPoolDomain:
    Type: String
    Description: Domain of the Cognito User Pool
  
  IdentityPoolId:
    Type: String
    Description: ID of the Cognito Identity Pool
  
  OutputBucketName:
    Type: String
    Description: Name of the output S3 bucket
    
  SecurityAlertsTopicArn:
    Type: String
    Description: ARN of the security alerts SNS topic

Resources:
  # Auth Service Stack
  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/wga-cloudformation-${AWS::AccountId}/auth.yaml'
      Parameters:
        Environment: !Ref Environment
        CognitoUserPoolId: !Ref UserPoolId
        CognitoClientId: !Ref UserPoolClientId
        CognitoDomain: !Ref UserPoolDomain
        CognitoIdentityPoolId: !Ref IdentityPoolId
        DeveloperMode: !Ref DeveloperMode
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # # Security Analytics Stack
  # SecurityAnalyticsStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub 'https://s3.amazonaws.com/wga-cloudformation-${AWS::AccountId}/security-analytics.yaml'
  #     Parameters:
  #       Environment: !Ref Environment
  #       CognitoUserPoolId: !Ref UserPoolId
  #       CognitoClientId: !Ref UserPoolClientId
  #       CognitoDomain: !Ref UserPoolDomain
  #       CognitoIdentityPoolId: !Ref IdentityPoolId
  #       OutputBucketName: !Ref OutputBucketName
  #       SecurityAlertsTopicArn: !Ref SecurityAlertsTopicArn
  #     Tags:
  #       - Key: Environment
  #         Value: !Ref Environment

  # # Zero Trust Stack
  # ZeroTrustStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub 'https://s3.amazonaws.com/wga-cloudformation-${AWS::AccountId}/zero-trust.yaml'
  #     Parameters:
  #       Environment: !Ref Environment
  #       CognitoUserPoolId: !Ref UserPoolId
  #       CognitoClientId: !Ref UserPoolClientId
  #       CognitoDomain: !Ref UserPoolDomain
  #       CognitoIdentityPoolId: !Ref IdentityPoolId
  #       SecurityAlertsTopicArn: !Ref SecurityAlertsTopicArn
  #     Tags:
  #       - Key: Environment
  #         Value: !Ref Environment

Outputs:
  CognitoDomain:
    Description: Cognito User Pool Domain
    Value: !Ref UserPoolDomain

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClientId